name: online_grocery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_staggered_grid_view: ^0.3.0
  floating_search_bar: ^0.3.0
  intl: ^0.15.8
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg.png
    - assets/cart.png
    - assets/map.png
    - assets/groceries/001-beetroot.png
    - assets/groceries/002-carrot.png
    - assets/groceries/003-apple.png
    - assets/groceries/004-apricot.png
    - assets/groceries/005-avocado.png
    - assets/groceries/006-bananas.png
    - assets/groceries/007-Bell pepper.png
    - assets/groceries/008-berry.png
    - assets/groceries/009-blueberry.png
    - assets/groceries/010-eggplant.png
    - assets/groceries/011-broccoli.png
    - assets/groceries/012-Capsicum.png
    - assets/groceries/013-cauliflower.png
    - assets/groceries/014-corn.png
    - assets/groceries/015-dragon fruit.png
    - assets/groceries/017-garlic.png
    - assets/groceries/018-green-chili-pepper.png
    - assets/groceries/019-okra.png
    - assets/groceries/020-lemon.png
    - assets/groceries/021-mango.png
    - assets/groceries/022-orange.png
    - assets/groceries/023-papaya.png
    - assets/groceries/024-pear.png
    - assets/groceries/025-pomegranate.png
    - assets/groceries/026-pumpkin.png
    - assets/groceries/027-rose-apple.png
    - assets/groceries/028-strawberry.png
    - assets/groceries/029-tomato.png
    - assets/groceries/030-watermelon.png
    - assets/add_to_cart.png
    - assets/visa.png
    - assets/success.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
